### PR TITLE
Deploy to tomcat/lib by default

### PR DESCRIPTION
**Pull request by steveswinsburg**
Default the deploy to /lib
Add a tomcat8 properties so that the sakai.app.server property works, if specified
Fix typo in the default location map variable
Remove .classpath and .project from git
Add .gitignore

SMP-23

### CODE REVIEW

**Comment by ern** [comment]
+1

**Comment by ottenhoff** [comment]
So this means no more customizing catalina.properties? Awesome!

**Comment by steveswinsburg** [comment]
Yeah ideally we wouldn't need that jar scanning mod in catalina.properties
either.

**Comment by jonespm** [comment]
Well in Tomcat 8 the jar scanning change has to be put into the context.xml. So it would mean no changes to catalina.properties, just context.xml (for speed improvement) and server.xml (for many other changes). It seemed like we could change web.xml files all over the code to possibly avoid the context.xml, but with contrib and other tools, and the time investment, not sure how worthwhile that is.

**Comment by ern** [comment]
We could potentially look at deploying something for context.xml issue

**Comment by steveswinsburg** [comment]
Done. We should get a release of this so we can bind to it. Whats the process for releasing now? Any volunteers?

**Pull request merged**
